//
//	mappdial.h - interface of the MapPDIAL class (generated by Visual Studio)
//  Copyright(C) 2024 Michael E. Cressey
//
//	This program is free software : you can redistribute it and /or modify it under the terms of the
//	GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or
//	any later version.
//
//	This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
//	implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
//	You should have received a copy of the GNU General Public License along with this program.
//  If not, see https://www.gnu.org/licenses/
//
// 

/////////////////////////////////////////////////////////////////////////////
// MapPDIAL dialog
class MapPDIAL : public CDialog
{
// Construction
public:
	MapPDIAL(CWnd* pParent = NULL);   // standard constructor

// Dialog Data
	//{{AFX_DATA(MapPDIAL)
	enum { IDD = IDD_MAP_PROJD };
	int		m_projNum;
	//}}AFX_DATA
/*
	BOOL	doNone;
	BOOL	doEquidistantCyclindrical;
*/
// Overrides
	// ClassWizard generated virtual function overrides
	//{{AFX_VIRTUAL(MapPDIAL)
	protected:
	virtual void DoDataExchange(CDataExchange* pDX);    // DDX/DDV support
	//}}AFX_VIRTUAL

// Implementation
protected:

	// Generated message map functions
	//{{AFX_MSG(MapPDIAL)
	//}}AFX_MSG
	DECLARE_MESSAGE_MAP()
public:
};
