//
//	ThinDlg.cpp - implementation of the ThinDlg class (generated by Visual Studio)
//  Copyright(C) 2024 Michael E. Cressey
//
//	This program is free software : you can redistribute it and /or modify it under the terms of the
//	GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or
//	any later version.
//
//	This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
//	implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
//
//	You should have received a copy of the GNU General Public License along with this program.
//  If not, see https://www.gnu.org/licenses/
//

#include "pch.h"
#include "mapviewSD.h"
#include "thindlg.h"

#ifdef _DEBUG
#undef THIS_FILE
static char BASED_CODE THIS_FILE[] = __FILE__;
#endif

/////////////////////////////////////////////////////////////////////////////
// ThinDlg dialog


ThinDlg::ThinDlg(CWnd* pParent /*=NULL*/)
	: CDialog(ThinDlg::IDD, pParent)
{
	//{{AFX_DATA_INIT(ThinDlg)
	m_checked = FALSE;
	m_value = _T("");
	//}}AFX_DATA_INIT
}


void ThinDlg::DoDataExchange(CDataExchange* pDX)
{
	CDialog::DoDataExchange(pDX);
	//{{AFX_DATA_MAP(ThinDlg)
	DDX_Check(pDX, IDC_CHECK1, m_checked);
	DDX_Text(pDX, IDC_EDIT1, m_value);
	//}}AFX_DATA_MAP
}


BEGIN_MESSAGE_MAP(ThinDlg, CDialog)
	//{{AFX_MSG_MAP(ThinDlg)
		// NOTE: the ClassWizard will add message map macros here
	//}}AFX_MSG_MAP
END_MESSAGE_MAP()


/////////////////////////////////////////////////////////////////////////////
// ThinDlg message handlers
